/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct word {
	char a[120];
};
typedef struct word word;

#define ECHO_PROG 6319
#define ECHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ECHO 1
extern  word * echo_1(word *, CLIENT *);
extern  word * echo_1_svc(word *, struct svc_req *);
extern int echo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ECHO 1
extern  word * echo_1();
extern  word * echo_1_svc();
extern int echo_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_word (XDR *, word*);

#else /* K&R C */
extern bool_t xdr_word ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ECHO_H_RPCGEN */
