#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double sum_avg;
double array[100];
int x;
int n;
int j;
int temp;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int z;
  sum_avg = 0;

  /* iterate until end of number of times (data_len) */
  for( z = 1; z <= input->input_data.input_data_len; z++)
    {
    sum_avg = sum_avg + *dp;  /* add what ptrs points  to ( '*' gets content ) */
    array[z] = *dp;
    dp++;
    }
    n = (input->input_data.input_data_len) + 1;
    for (x = 0; x < n; ++x) 
    {
        for (j = x + 1; j < n; ++j)
        {
            if (array[x] > array[j]) 
            {
                temp =  array[x];
                array[x] = array[j];
                array[j] = temp;
            }
 
        }
    }
 
 if((n-1)%2 == 0)
 {
	sum_avg  = (array[(n-1)/2] + array[(n+1)/2])/2.0;   //Even number.
 }
 else
 {
	 sum_avg = array[n/2]; //Odd number.
 }

  return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
