#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include "stdlib.h"
/* run locally on 'server' called by a remote client. */
static double sum_avg;
float array[1000];
int x;
int n;
int j;
int w;
int v;
int c;
int temp;
double flag;
char string[1000] = "";
char otString[1000] ="";

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
char * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int z;
  sum_avg = 0;

  /* iterate until end of number of times (data_len) */
  for( z = 0; z < input->input_data.input_data_len; z++)
    {
    sum_avg = sum_avg + *dp;  /* add what ptrs points  to ( '*' gets content ) */
	if (z == 0)
	{
		flag = *dp;
		dp++;
	}
	else
	{
    array[z] = *dp;
    dp++;
	}
    }
    n = (input->input_data.input_data_len) + 1;
	
	
	//printf("FLAG IS %.0f\n", flag);
	
	//ASCENDING ORDER 
if(flag == 100)
{
    for (x = 1; x < n; ++x) 
    {
        for (j = x + 1; j < n; ++j)
        {
            if (array[x] > array[j]) 
            {
                temp =  array[x];
                array[x] = array[j];
                array[j] = temp;
            }
 
        }
    }
 printf("ASCENDING\n");
	 for (w = 2; w < n; w++)
 {
	 //printf("%.0f\n",array[w]);
	 //printf("%.0f\n",array[w]);
	 sprintf(otString, "%.0f ", array[w]);
	 strcat(string, otString);
	 //printf(" %s", string);
 }
  for (c = 2; c < n; c++)
	{
	 printf("%.0f\n",array[c]);
	}
}
//DESCEND ORDER
if(flag == 101)
{
    for (x = 1; x < n; ++x) 
    {
        for (j = x + 1; j < n; ++j)
        {
            if (array[x] < array[j]) 
            {
                temp =  array[x];
                array[x] = array[j];
                array[j] = temp;
            }
 
        }
    }
 printf("DESCENDING\n");
 for (w = 1; w < n-1; w++)
	{
	 //printf("%.0f\n",array[w]);
	 sprintf(otString, "%.0f ", array[w]);
	 strcat(string, otString);
	 //printf(" %s", string);
	}
	
	
 for (v = 1; v < n-1; v++)
	{
	 printf("%.0f\n",array[v]);
	}
}
 printf("TEST: %s\n", string);
 return string;
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
char * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
  

  

